### ISSUE TITLE
Realtime but not continuous analysis ?

### ISSUE THREAD

**Issue by Bulinlinbu** [dlepaux/realtime-bpm-analyzer#15]
I try to use the nice package for a realtime BPM analysis with line / mic input using navigator.getUserMedia

BPM detection works fine, but I don't understand why the value is not updated when input BPM changes.

Maybe I made a mistake in my code (or comprehension), but I think the analyzer does not update BPM continiously.

Starting from [functionnal example](https://github.com/dlepaux/realtime-bpm-analyzer-example) edit app.js :
```
'use strict';

const RealTimeBPMAnalyzer = require('realtime-bpm-analyzer');

const App = {
  init() {

    var AudioContext = window.AudioContext || window.webkitAudioContext;
	
	navigator.getUserMedia = ( navigator.getUserMedia ||
                       navigator.webkitGetUserMedia ||
                       navigator.mozGetUserMedia ||
                       navigator.msGetUserMedia);
					   
	var context = new AudioContext();
	// Enable mic / line input watching
	navigator.getUserMedia({audio: true}, onStream.bind(this), function() {});

	function onStream(stream) {
		// Set the source with the HTML Audio Node
		var input = context.createMediaStreamSource(stream);
		// Set the scriptProcessorNode to get PCM data in real time
		var scriptProcessorNode = context.createScriptProcessor(4096, 1, 1);

		// Connect everythings together (do not connect input to context.destination to avoid sound looping)
		scriptProcessorNode.connect(context.destination);
		input.connect(scriptProcessorNode);

		var onAudioProcess = new RealTimeBPMAnalyzer({
			scriptNode: {
				bufferSize: 4096,
				numberOfInputChannels: 1,
				numberOfOutputChannels: 1
			},
			pushTime: 2000,
			pushCallback: function(err, bpm) {
				if(bpm && bpm.length)
					console.log('bpm', bpm[0].tempo);   // <= When stabilized, always displays the same BPM
			}
		});

		// Attach realTime function to audioprocess event.inputBuffer (AudioBuffer)
		scriptProcessorNode.onaudioprocess = function (e) {
			onAudioProcess.analyze(e);
		};
	}
	
  }
}

module.exports = App;
```

Any idea ?

**Comment by dlepaux** [comment]
Hello @Bulinlinbu 
Could you provide me a complete exemple with your usecase, i mean what you say/song or what do you want to test ?
Do you test multiple song ?
Thank you

**Comment by Bulinlinbu** [comment]
You can reproduce like this (in Windows) :
* First, be sure your sound card recording device is "Stereo mix" (it means every sound played in the computer) 
* Starting from your working example ([https://github.com/dlepaux/realtime-bpm-analyzer-example]) Put my above code (updated) in app.js
* build & serve & run 127.0.0.1:8080
* The browser asks you to allow access to your microphone, say "yes"
* Your sample song starts and console stabilize to 131 bpm - fine
* Pause the song and open oanother tab and go to YouTube on a video with a fixed BPM (here 140) like [https://www.youtube.com/watch?v=2vhnxYfWco8]
console still displays 131 bpm

Tested on Chrome 69

Thanks for your help ! :)

**Comment by dlepaux** [comment]
Hello @Bulinlinbu,
You have touch the limit of this package.. It can't analyze (non-stop) multiple song.
It is like if you Shazam something and switch to an other song during the scan !
If you have an idea to how to deal with your issue I'm listening you :)

**Comment by Bulinlinbu** [comment]
Hi David,
I understand the purpose of your package now. 

I have an idea, tell me if this approch can work :
By the way, I don't really understand why there is different thresolds in validPeaks, because each key (threshold) of validPeak object contains the same array : 
`this.validPeaks[Object.keys(this.validPeaks)[0]] === this.validPeaks[Object.keys(this.validPeaks)[1]] // true`

However, this array is growing each frame. So, we can build a rounding array, deleting older values, with a minimum of frame to guess the BPM properly. Hence, the calculated BPM will follow the music (with a latency of course).

Here is a piece of code to illustrate, in the callback function :

```
// Important : in index.js of the package, disable clearing peaks on line 184
// consider a global var indexBuffer = [];
pushCallback: function(err, bpm) {
  if(bpm && bpm.length)
    console.log('bpm', bpm[0].tempo);   

    // Store the size of the peaks array
    const firstThreshold = Object.keys(onAudioProcess.validPeaks)[0];
    indexBuffer.push(onAudioProcess.validPeaks[firstThreshold].length);

    // If we have more than 5 frames (can be adjusted), we delete older peaks
    while(indexBuffer.length >= 5) {
      const index = indexBuffer[0];
      for(let threshold of Object.keys(onAudioProcess.validPeaks)) {
        onAudioProcess.validPeaks[threshold].splice(0, index);
        break; // All arrays in onAudioProcess.validPeaks are the same...
      }

      // MAJ des autres index dans le buffer
      indexBuffer = indexBuffer.map(idx => idx - index);
      indexBuffer.shift();
  }
}
```

The BPM seems to be updated when you change the song - it's not perfect, there is odd values, due to small peak buffer.

**Comment by dlepaux** [comment]
We could set an 'event' after the stabilisation of the bpm and fix a limit for the validPeaks array equal to the duration of stabilisation ? What do you think about that ? Could you test that ?

**Comment by dlepaux** [comment]
@Bulinlinbu I develop a proto-solution for you, I keep you informed ;)

**Comment by dlepaux** [comment]
@Bulinlinbu I have something for you ! You can checkout and pull this repository `https://github.com/dlepaux/realtime-bpm-analyzer-example`, next execute `bash install.sh`. I have added a workflow to develop easier...
I let you checkout the `app/components/realtime-bpm-analyzer` repository to the `feature/continuous-analysis` branch.
Lauch the server and go to the userMedia exemple.
Thank you for your feedback

**Comment by dlepaux** [comment]
https://github.com/dlepaux/realtime-bpm-analyzer/pull/16
