### ISSUE TITLE
how to use this with an audio stream url? 

### ISSUE THREAD

**Issue by mrsydster** [dlepaux/realtime-bpm-analyzer#29]

**Comment by dlepaux** [comment]
Hello,

Can you be more precise about your use case ?

**Comment by mrsydster** [comment]
@dlepaux Hey David, I want to analyze a live url. So I am getting audio over an RTMP stream and analyze the BMP realtime from that url

**Comment by dlepaux** [comment]
I recommend you to see an exemple I provide in this repository: `https://github.com/dlepaux/realtime-bpm-analyzer-exemple` file: `app/js/userMedia.js`.

In this exemple I'm using the microphone as a stream source. I think it's quite similar to what you want to do.

Let me know if you succeeded or need some help !

I would be glad to add this case as a new usage exemple.

Thanks
