### ISSUE TITLE
createScriptProcessor deprecation

### ISSUE THREAD

**Issue by LennyPenny** [dlepaux/realtime-bpm-analyzer#38]
Hey, 
awesome job on this! 

I had a look through the code and noticed it uses [`createScriptProcessor`](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor) to process the audio data. 
This seems to be deprecated now and `AudioWorklets` are the replacement. 

Do you have any plans to switch over to those?

**Comment by dlepaux** [comment]
Hello @LennyPenny,

Yes I know that and nothing is done about it yet.

Feel free to make a Pull Request, your help would be really appreciated here !

If not it will be done when I will have the time to do it (I can't give you a date).

**Comment by dlepaux** [comment]
Hi @LennyPenny 
I'm currently preparing a major release that includes the migration to `AudioWorklets`, TypeScript and an Event driven design instead of callback function in the configuration.
Stay tuned :)

**Comment by dlepaux** [comment]
Hello @LennyPenny,
I've just release the v3 of the library that use `AudioWorklets`, enjoy
