### ISSUE TITLE
Remove the need to expose the processor file

### ISSUE THREAD

**Issue by evoyy** [dlepaux/realtime-bpm-analyzer#50]
I have seen other web audio projects using the following technique to register audio worklets without the need to expose a separate file. 

````javascript
import {processor} from '../src/processor';

const blob = new Blob([processor], {type: 'application/javascript'});
const objectURL = URL.createObjectURL(blob);
await audioContext.audioWorklet.addModule(objectURL);
const audioWorkletNode = new AudioWorkletNode(audioContext, processorName);
````

Have you tried this? If it works it would make deployment and upgrade much simpler and avoid issues with caching, CORS, and HTTPS.

An example of this technique can be seen here:

https://github.com/esonderegger/web-audio-peak-meter/blob/759c119d832b73d9e81e9bca91baa7d6264dc62e/src/index.ts#L47-L60

**Comment by dlepaux** [comment]
Thanks for the feedback ! I've implemented and tested the approach successfully.

**Comment by dlepaux** [comment]
Fixed here: https://github.com/dlepaux/realtime-bpm-analyzer/releases/tag/v3.2.0

**Comment by evoyy** [comment]
Awesome! Well done! This project has a lot of potential. If I have any other ideas I will let you know!
